### ISSUE TITLE
プランの仕組みを調べる

### ISSUE THREAD

**Issue by pndcat** [tokyorubykaigi12/sponsor-app#3]
プランの capacity に対してスポンサー数が達していたり、close (plan に紐づいている期限がすぎているかどうか) を見るロジックがある。
Ruby, Zero は選択ができない＆受付終了のラベルが出ている

<img width="1157" alt="ss 2024-09-16 23 06 56" src="https://github.com/user-attachments/assets/2eb5e4bb-9a12-4d22-b79f-12aeb8073271">

## 「プランの capacity に対してスポンサー数が達しているか」どうかの実装

この実装間違えている気がする…
`sponsorships.active.count > capacity` の実装だと、capacity = 確定枠の場合 true にならない

なんでRubyKaigiで問題になっていないのかというと、sold_out? じゃなくて closed? のほうで「受付終了」になるからっぽい

https://github.com/tokyorubykaigi12/sponsor-app/blob/4d36735fef0cf10d018e16f1aeefcee9ed3afdcc/app/views/sponsorships/_form.html.haml#L106-L120

https://github.com/tokyorubykaigi12/sponsor-app/blob/4d36735fef0cf10d018e16f1aeefcee9ed3afdcc/app/models/plan.rb#L17-L19

**Comment by pndcat** [comment]
会社に Accepted をすると、受付終了になるのは確認できた（今はcapacity＋1個分を確定させる必要があるが）

Admin画面

<img width="1178" alt="ss 2024-09-16 23 10 27" src="https://github.com/user-attachments/assets/b7226725-9e3d-432d-b6b5-50b6746d1892">

<img width="388" alt="ss 2024-09-16 23 10 35" src="https://github.com/user-attachments/assets/051dc895-fb71-486d-9638-935826c7cd68">

応募フォーム側

<img width="1157" alt="ss 2024-09-16 23 06 56" src="https://github.com/user-attachments/assets/85d55fa4-2872-45d5-b640-c70bdd19fe54">

**Comment by osyoyu** [comment]
accept しない限りは capacity に対してまったくカウントされないということか
https://github.com/tokyorubykaigi12/sponsor-app/blob/4d36735fef0cf10d018e16f1aeefcee9ed3afdcc/app/models/sponsorship.rb#L50
